#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n?", re.DOTALL)


def parse_skill(skill_path: Path) -> tuple[dict[str, str], str]:
    text = skill_path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError(f"{skill_path} is missing YAML frontmatter.")

    metadata: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip("'").strip('"')

    if "name" not in metadata or "description" not in metadata:
        raise ValueError(f"{skill_path} must define both name and description in frontmatter.")

    body = text[match.end():].strip()
    return metadata, body


def iter_skill_dirs(repo_root: Path) -> list[Path]:
    return sorted(
        skill_dir
        for skill_dir in repo_root.iterdir()
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists()
    )


def command_prompt(skill_dir: Path, metadata: dict[str, str], body: str) -> str:
    return (
        "Use the shared skill below as the primary workflow for this request.\n\n"
        f"Skill folder: {skill_dir.name}\n"
        f"Skill name: {metadata['name']}\n"
        f"Skill description: {metadata['description']}\n\n"
        "Resolve any relative paths mentioned in the skill body relative to this skill folder, "
        f"not the current working directory: {skill_dir.as_posix()}\n\n"
        "If the user supplied extra command arguments, treat them as additional task context.\n\n"
        f"{body}\n\n"
        "Extra command arguments:\n{{args}}\n"
    )


def write_command_file(skill_dir: Path, output_path: Path) -> None:
    metadata, body = parse_skill(skill_dir / "SKILL.md")
    prompt = command_prompt(skill_dir, metadata, body)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "# Generated by scripts/export-gemini-skill.py. Do not edit by hand.\n"
        f"description = {json.dumps(metadata['description'], ensure_ascii=False)}\n"
        f"prompt = {json.dumps(prompt, ensure_ascii=False)}\n",
        encoding="utf-8",
    )


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    registry = json.loads((repo_root / "scripts" / "skill-registry.json").read_text(encoding="utf-8"))

    parser = argparse.ArgumentParser(
        description="Export repo skills into Gemini CLI project commands."
    )
    parser.add_argument(
        "skill_names",
        nargs="*",
        help="Optional skill folder names to export. Use --all to export every skill.",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Export every skill folder in the repository.",
    )
    parser.add_argument(
        "--output-root",
        default=str(repo_root / ".gemini" / "commands" / registry["gemini_namespace"]),
        help="Directory that will receive generated Gemini command TOML files.",
    )
    args = parser.parse_args()

    skill_dirs = iter_skill_dirs(repo_root)
    skill_map = {skill_dir.name: skill_dir for skill_dir in skill_dirs}

    if args.all or not args.skill_names:
        selected = skill_dirs
    else:
        missing = [name for name in args.skill_names if name not in skill_map]
        if missing:
            raise SystemExit(f"Unknown skill folder(s): {', '.join(missing)}")
        selected = [skill_map[name] for name in args.skill_names]

    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    existing = {path.stem: path for path in output_root.rglob("*.toml")}
    selected_names = {skill_dir.name for skill_dir in selected}

    for stale_name, stale_path in existing.items():
        if stale_name not in selected_names and args.all:
            stale_path.unlink()

    for skill_dir in selected:
        write_command_file(skill_dir, output_root / f"{skill_dir.name}.toml")

    print(
        json.dumps(
            {
                "exported": [skill_dir.name for skill_dir in selected],
                "output_root": str(output_root),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
